### ISSUE TITLE
Would you be willing to provide a tutorial on how to start the training process?

### ISSUE THREAD

**Issue by Hou-jing** [speedcell4/nersted#2]
I got the code but don't know how to run it, when I try to add parameters in "__main__.py" it gives me an error.
![image](https://user-images.githubusercontent.com/75936962/189635735-e3d5ab3e-2059-47ce-ad19-7b7f017cebfa.png)

**Comment by speedcell4** [comment]
I have already provided the complete commands, please read the [Training section](https://github.com/speedcell4/nersted#ace2004-dataset) carefully.

And, please run it in the terminal instead of in PyCharm, since this is the simplest way to do it.

Besides, `aku` generates the command interface by inspecting the function's signature. Therefore, if you want to add parameters you should change the arguments of function `train_tagger`.

**Comment by speedcell4** [comment]
Open your terminal, just 4 steps, please post your error information if it still does not work.

```bash
git clone https://github.com/speedcell4/nersted.git

cd nersted

python3 -m pip install -r requirements.txt

CUDA_VISIBLE_DEVICES=0 python3 -m ner --data ace2004 \
  --study ace2004-naive \
  --dec NaiveDecoder \
  --lr 0.03 --gamma 0.02 --momentum 0.9 \
  --use_bert false --use_flair false
```
